"""Convert sniffle/advdata/constants.py Python dicts into a Rust module
with sorted-by-key static slices so we can use binary_search_by_key."""
import re
import sys

src_path = "Sniffle/python_cli/sniffle/advdata/constants.py"

# Also include the missing service_uuids16 table generated by Python's
# constants_generator.py — but the committed constants.py only has the
# 3 dicts visible above. Let's parse what's there.

# Read source, find each top-level dict, parse entries.
src = open(src_path).read()

def parse_dict(name, src):
    """Parse a 'name = { 0xKEY: 'value', ... }' block. Returns list of (int, str)."""
    m = re.search(rf'^{name}\s*=\s*\{{\n(.*?)^\}}', src, re.MULTILINE | re.DOTALL)
    if not m:
        return None
    body = m.group(1)
    out = []
    for line in body.splitlines():
        ln = line.strip().rstrip(',')
        if not ln or ln.startswith('#'):
            continue
        # 0xKEY: 'value' (value may contain escaped quotes)
        m2 = re.match(r"0x([0-9A-Fa-f]+)\s*:\s*'(.*)'$", ln)
        if not m2:
            # Possibly multi-line — skip silently for now
            continue
        key = int(m2.group(1), 16)
        val = m2.group(2)
        out.append((key, val))
    return out

companies = parse_dict('company_identifiers', src)
ad_types  = parse_dict('ad_types', src)
service16 = parse_dict('service_uuids16', src) or []

print(f"// generated from sniffle/advdata/constants.py", file=sys.stderr)
print(f"// company_identifiers: {len(companies)}", file=sys.stderr)
print(f"// ad_types: {len(ad_types)}", file=sys.stderr)
print(f"// service_uuids16: {len(service16)}", file=sys.stderr)

def emit(name, kw_type, entries):
    """Emit a `pub static NAME: &[(KW_TYPE, &'static str)] = &[...]` sorted by key."""
    entries.sort()
    print(f"\npub static {name}: &[({kw_type}, &str)] = &[")
    for k, v in entries:
        # Escape backslash and double-quote
        v_esc = v.replace('\\', '\\\\').replace('"', '\\"')
        if kw_type == 'u16':
            print(f'    (0x{k:04X}, "{v_esc}"),')
        elif kw_type == 'u8':
            print(f'    (0x{k:02X}, "{v_esc}"),')
        else:
            print(f'    (0x{k:X}, "{v_esc}"),')
    print("];")

print("// AUTO-GENERATED — do not edit. See gen_advdata_constants.py")
print("// Source: Sniffle/python_cli/sniffle/advdata/constants.py")
print("// Bluetooth Assigned Numbers, Copyright Bluetooth SIG, used under their license.")
print()
print("#![allow(clippy::unreadable_literal)]")
emit("COMPANY_IDENTIFIERS", "u16", companies)
emit("AD_TYPES", "u8", ad_types)
emit("SERVICE_UUIDS16", "u16", service16)
