//! End-to-end loopback test: in-process [`btidalpool-server`] + in-process
//! [`btidalpool-client`] calls, real TLS (self-signed cert generated by
//! `rcgen` at test time), mocked OAuth/ingest/query so the test has no
//! external dependencies.
//!
//! These tests satisfy task requirement #5 — "the full logic can still be
//! tested locally with unit tests before pushing changes to the server" —
//! at the integration boundary (HTTP+TLS+codec+handlers in one shot).
//!
//! Each test:
//!
//!   1. Generates a fresh self-signed TLS cert + key for `localhost`.
//!   2. Picks an unused port (bind 127.0.0.1:0, then read back the assigned
//!      port from the server before launching the HTTPS listener).
//!   3. Starts the server in a background thread with mocked dependencies.
//!   4. Builds a client `Transport` pinned to the generated cert.
//!   5. Round-trips one or more requests and asserts on the responses.
//!
//! Important: we don't share state across tests. Each test spins up its own
//! server, so tests can run in parallel without contention.

use std::net::{IpAddr, Ipv4Addr, SocketAddr, TcpListener};
use std::path::PathBuf;
use std::sync::Arc;
use std::thread;
use std::time::Duration;

use btidalpool_client::transport::{CertTrust, Transport};
use btidalpool_client::{build_check_hash, build_query, build_upload};
use btidalpool_proto::{
    canonical_sha1, AuthFields, ErrorKind, Payload, QueryParams, Response,
};
use btidalpool_server::handlers::Deps;
use btidalpool_server::http::{self, Config as ServerConfig, TlsConfig};
use btidalpool_server::ingest::NoopIngestSink;
use btidalpool_server::oauth::{MockOAuthValidator, OAuthValidator};
use btidalpool_server::query::{QueryEngine, StubQueryEngine};
use btidalpool_server::rate_limit::{Limiter, Limits};
use btidalpool_server::state::ServerState;

/// Self-contained test harness: temp dirs, generated TLS cert/key, picked
/// port, running server thread, configured client.
struct Harness {
    _td: tempfile::TempDir,
    server_url: String,
    cert_path: PathBuf,
    auth: AuthFields,
}

impl Harness {
    fn boot(query: Arc<dyn QueryEngine>, good_token: &str, email: &str) -> Self {
        let td = tempfile::tempdir().unwrap();

        // 1) Cert + key for `localhost`. rcgen produces a self-signed cert
        //    by default which is exactly what we need for a loopback test.
        let mut params = rcgen::CertificateParams::new(vec!["localhost".to_string()]).unwrap();
        params
            .subject_alt_names
            .push(rcgen::SanType::IpAddress(IpAddr::V4(Ipv4Addr::LOCALHOST)));
        let key_pair = rcgen::KeyPair::generate().unwrap();
        let cert = params.self_signed(&key_pair).unwrap();
        let cert_pem = cert.pem();
        let key_pem = key_pair.serialize_pem();
        let cert_path = td.path().join("cert.pem");
        let key_path = td.path().join("key.pem");
        std::fs::write(&cert_path, &cert_pem).unwrap();
        std::fs::write(&key_path, &key_pem).unwrap();

        // 2) Pick an unused port by binding a TcpListener and then dropping
        //    it. There's a tiny race window between drop and the server's
        //    own bind, but the OS doesn't normally reuse a just-dropped
        //    port within microseconds — and if it did, the test would fail
        //    loudly rather than silently misbehave.
        let listener = TcpListener::bind("127.0.0.1:0").unwrap();
        let port = listener.local_addr().unwrap().port();
        drop(listener);
        let bind = SocketAddr::from(([127, 0, 0, 1], port));

        // 3) Build the server config.
        let state = ServerState::initialize(
            td.path().join("pool"),
            td.path().join("ul"),
            td.path().join("ac"),
        )
        .unwrap();
        let validator: Arc<dyn OAuthValidator> = Arc::new(MockOAuthValidator {
            good_token: good_token.into(),
            email: email.into(),
        });
        let limiter = Limiter::new(Limits::default());
        let deps = Deps {
            state,
            ingest: Arc::new(NoopIngestSink),
            query,
        };
        let cfg = ServerConfig {
            bind,
            tls: Some(TlsConfig {
                cert_pem_path: cert_path.clone(),
                key_pem_path: key_path.clone(),
            }),
            limiter,
            validator,
            deps,
        };

        // 4) Run the server in a detached thread. We never join it — the
        //    process exit at test-binary teardown takes the thread with it.
        //    `http::run` only returns on a fatal accept error; treating it
        //    as a hard failure here lets us surface the cause if the bind
        //    fails (e.g. the cert PEM is malformed somehow).
        thread::spawn(move || {
            if let Err(e) = http::run(cfg) {
                eprintln!("server thread exited: {e}");
            }
        });

        // 5) Wait until the server is accepting connections. Without this
        //    the first client request would race the listener and we'd get
        //    a transport error. Bounded retry so a real failure doesn't
        //    hang the test forever.
        let url = format!("https://localhost:{port}");
        let deadline = std::time::Instant::now() + Duration::from_secs(5);
        loop {
            if std::net::TcpStream::connect_timeout(&bind, Duration::from_millis(200)).is_ok() {
                break;
            }
            if std::time::Instant::now() > deadline {
                panic!("server did not start listening within 5s");
            }
            thread::sleep(Duration::from_millis(50));
        }

        Self {
            _td: td,
            server_url: url,
            cert_path,
            auth: AuthFields {
                token: good_token.into(),
                refresh_token: "refresh".into(),
                use_test_db: false,
            },
        }
    }

    fn client(&self) -> Transport {
        Transport::new(
            self.server_url.clone(),
            CertTrust::Pinned {
                ca_pem_path: self.cert_path.clone(),
            },
        )
        .unwrap()
    }
}

#[test]
fn check_hash_unknown_returns_ok() {
    let h = Harness::boot(
        Arc::new(StubQueryEngine::ok(b"[]".to_vec(), 0)),
        "good-tok",
        "tester@example.com",
    );
    let resp = h
        .client()
        .round_trip(&build_check_hash(h.auth.clone(), "deadbeef".into()))
        .unwrap();
    match resp {
        Response::Ok { message } => assert!(message.contains("does not yet exist")),
        other => panic!("wrong variant: {other:?}"),
    }
}

#[test]
fn invalid_token_returns_unauthorized() {
    let h = Harness::boot(
        Arc::new(StubQueryEngine::ok(b"[]".to_vec(), 0)),
        "good-tok",
        "tester@example.com",
    );
    let bad = AuthFields {
        token: "wrong".into(),
        refresh_token: "rt".into(),
        use_test_db: false,
    };
    let resp = h
        .client()
        .round_trip(&build_check_hash(bad, "deadbeef".into()))
        .unwrap();
    match resp {
        Response::Err { kind, .. } => assert_eq!(kind, ErrorKind::Unauthorized),
        other => panic!("wrong variant: {other:?}"),
    }
}

#[test]
fn upload_then_check_hash_round_trip() {
    let h = Harness::boot(
        Arc::new(StubQueryEngine::ok(b"[]".to_vec(), 0)),
        "good-tok",
        "tester@example.com",
    );
    let payload = br#"[{"bdaddr":"AA:BB:CC:DD:EE:FF","bdaddr_rand":0}]"#.to_vec();
    let hash = canonical_sha1(&payload).unwrap();

    // Pre-flight: server doesn't have it yet.
    let pre = h
        .client()
        .round_trip(&build_check_hash(h.auth.clone(), hash.clone()))
        .unwrap();
    assert!(
        matches!(pre, Response::Ok { .. }),
        "expected Ok before upload, got {pre:?}"
    );

    // Upload.
    let up = h
        .client()
        .round_trip(&build_upload(h.auth.clone(), payload.clone()))
        .unwrap();
    match up {
        Response::Ok { message } => assert!(message.contains("saved successfully")),
        other => panic!("upload should succeed, got {other:?}"),
    }

    // Post-check: server now reports the hash as present.
    let post = h
        .client()
        .round_trip(&build_check_hash(h.auth.clone(), hash.clone()))
        .unwrap();
    match post {
        Response::Err { kind, .. } => assert_eq!(kind, ErrorKind::DuplicateUpload),
        other => panic!("expected DuplicateUpload after upload, got {other:?}"),
    }

    // Second upload of the same bytes is rejected.
    let dup = h
        .client()
        .round_trip(&build_upload(h.auth.clone(), payload))
        .unwrap();
    match dup {
        Response::Err { kind, .. } => assert_eq!(kind, ErrorKind::DuplicateUpload),
        other => panic!("expected DuplicateUpload, got {other:?}"),
    }
}

#[test]
fn query_returns_canned_bytes_through_full_stack() {
    let h = Harness::boot(
        Arc::new(StubQueryEngine::ok(b"[1,2,3]".to_vec(), 3)),
        "good-tok",
        "tester@example.com",
    );
    let resp = h
        .client()
        .round_trip(&build_query(h.auth.clone(), QueryParams::default()))
        .unwrap();
    match resp {
        Response::QueryResult {
            records,
            btides_json,
        } => {
            assert_eq!(records, 3);
            assert_eq!(btides_json, b"[1,2,3]");
        }
        other => panic!("wrong variant: {other:?}"),
    }
}

#[test]
fn query_empty_returns_empty_result_kind() {
    let h = Harness::boot(
        Arc::new(StubQueryEngine::empty()),
        "good-tok",
        "tester@example.com",
    );
    let resp = h
        .client()
        .round_trip(&build_query(h.auth.clone(), QueryParams::default()))
        .unwrap();
    match resp {
        Response::Err { kind, .. } => assert_eq!(kind, ErrorKind::EmptyResult),
        other => panic!("wrong variant: {other:?}"),
    }
}

#[test]
fn rate_limit_returns_429_when_daily_budget_exhausted() {
    // Boot a server with a per-day budget of 1, then make two calls. The
    // second should come back as a 429 even though the response body itself
    // is text/plain (the rate-limit gate fires before the codec layer).
    let td = tempfile::tempdir().unwrap();
    let mut params = rcgen::CertificateParams::new(vec!["localhost".to_string()]).unwrap();
    params
        .subject_alt_names
        .push(rcgen::SanType::IpAddress(IpAddr::V4(Ipv4Addr::LOCALHOST)));
    let key_pair = rcgen::KeyPair::generate().unwrap();
    let cert = params.self_signed(&key_pair).unwrap();
    let cert_path = td.path().join("cert.pem");
    let key_path = td.path().join("key.pem");
    std::fs::write(&cert_path, cert.pem()).unwrap();
    std::fs::write(&key_path, key_pair.serialize_pem()).unwrap();
    let listener = std::net::TcpListener::bind("127.0.0.1:0").unwrap();
    let port = listener.local_addr().unwrap().port();
    drop(listener);
    let bind = SocketAddr::from(([127, 0, 0, 1], port));

    let state = ServerState::initialize(
        td.path().join("pool"),
        td.path().join("ul"),
        td.path().join("ac"),
    )
    .unwrap();
    let cfg = ServerConfig {
        bind,
        tls: Some(TlsConfig {
            cert_pem_path: cert_path.clone(),
            key_pem_path: key_path,
        }),
        limiter: Limiter::new(Limits {
            max_simultaneous: 10,
            max_per_day: 1,
            window: Duration::from_secs(3600),
        }),
        validator: Arc::new(MockOAuthValidator {
            good_token: "good".into(),
            email: "u@e.com".into(),
        }),
        deps: Deps {
            state,
            ingest: Arc::new(NoopIngestSink),
            query: Arc::new(StubQueryEngine::ok(b"[]".to_vec(), 0)),
        },
    };
    std::thread::spawn(move || {
        let _ = http::run(cfg);
    });

    // Wait for the listener.
    let deadline = std::time::Instant::now() + Duration::from_secs(5);
    loop {
        if std::net::TcpStream::connect_timeout(&bind, Duration::from_millis(200)).is_ok() {
            break;
        }
        if std::time::Instant::now() > deadline {
            panic!("server did not start listening within 5s");
        }
        std::thread::sleep(Duration::from_millis(50));
    }

    let url = format!("https://localhost:{port}");
    let auth = AuthFields {
        token: "good".into(),
        refresh_token: "rt".into(),
        use_test_db: false,
    };

    let t = Transport::new(
        url,
        CertTrust::Pinned {
            ca_pem_path: cert_path,
        },
    )
    .unwrap();

    // First call consumes the daily budget.
    let _ = t
        .round_trip(&build_check_hash(auth.clone(), "abc".into()))
        .unwrap();
    // Second call hits the rate limiter, which short-circuits to plain
    // text — round_trip() should report a transport-layer error containing
    // "Too Many Requests" rather than returning a typed Response.
    let err = t
        .round_trip(&build_check_hash(auth, "abc".into()))
        .unwrap_err();
    let s = format!("{err:#}");
    assert!(
        s.contains("Too Many Requests") || s.contains("text/plain"),
        "expected rate-limited error, got {s}"
    );
}

#[test]
fn wrong_content_type_is_rejected_at_http_layer() {
    let h = Harness::boot(
        Arc::new(StubQueryEngine::ok(b"[]".to_vec(), 0)),
        "good-tok",
        "tester@example.com",
    );
    // Use ureq directly so we can force a wrong Content-Type. The server
    // should respond with HTTP 415 and a text/plain body explaining the
    // expected media type.
    let agent = build_insecure_agent();
    let resp = agent
        .post(&h.server_url)
        .set("Content-Type", "application/json")
        .send_bytes(b"{}");
    match resp {
        Err(ureq::Error::Status(415, r)) => {
            let body = r.into_string().unwrap();
            assert!(body.contains("Unsupported Media Type"));
            assert!(body.contains("application/x-btidalpool-cbor-zstd"));
        }
        Ok(r) => panic!("expected 415, got {}", r.status()),
        Err(e) => panic!("expected 415 error, got: {e}"),
    }
}

#[test]
fn wrong_http_method_is_rejected() {
    let h = Harness::boot(
        Arc::new(StubQueryEngine::ok(b"[]".to_vec(), 0)),
        "good-tok",
        "tester@example.com",
    );
    let agent = build_insecure_agent();
    let resp = agent.get(&h.server_url).call();
    match resp {
        Err(ureq::Error::Status(405, _)) => {}
        Ok(r) => panic!("expected 405, got {}", r.status()),
        Err(e) => panic!("expected 405 error, got: {e}"),
    }
}

/// Install rustls's `ring` provider once per process so the integration
/// tests' direct calls to `ClientConfig::builder()` (in `build_insecure_agent`)
/// don't panic. Matches the same once-per-process install the production
/// `Transport::new` does internally.
fn ensure_crypto_provider_installed() {
    use std::sync::Once;
    static ONCE: Once = Once::new();
    ONCE.call_once(|| {
        let _ = rustls::crypto::ring::default_provider().install_default();
    });
}

/// Build a ureq agent that trusts any TLS cert. The fact that we need this
/// inside the integration tests is itself a confirmation that
/// `--insecure` works end-to-end through rustls.
fn build_insecure_agent() -> ureq::Agent {
    ensure_crypto_provider_installed();
    use rustls::client::danger::{
        HandshakeSignatureValid, ServerCertVerified, ServerCertVerifier,
    };
    use rustls::pki_types::{CertificateDer, ServerName, UnixTime};
    use rustls::{ClientConfig, DigitallySignedStruct, SignatureScheme};
    #[derive(Debug)]
    struct AcceptAll;
    impl ServerCertVerifier for AcceptAll {
        fn verify_server_cert(
            &self,
            _: &CertificateDer<'_>,
            _: &[CertificateDer<'_>],
            _: &ServerName<'_>,
            _: &[u8],
            _: UnixTime,
        ) -> std::result::Result<ServerCertVerified, rustls::Error> {
            Ok(ServerCertVerified::assertion())
        }
        fn verify_tls12_signature(
            &self,
            _: &[u8],
            _: &CertificateDer<'_>,
            _: &DigitallySignedStruct,
        ) -> std::result::Result<HandshakeSignatureValid, rustls::Error> {
            Ok(HandshakeSignatureValid::assertion())
        }
        fn verify_tls13_signature(
            &self,
            _: &[u8],
            _: &CertificateDer<'_>,
            _: &DigitallySignedStruct,
        ) -> std::result::Result<HandshakeSignatureValid, rustls::Error> {
            Ok(HandshakeSignatureValid::assertion())
        }
        fn supported_verify_schemes(&self) -> Vec<SignatureScheme> {
            vec![
                SignatureScheme::RSA_PKCS1_SHA256,
                SignatureScheme::RSA_PKCS1_SHA384,
                SignatureScheme::RSA_PKCS1_SHA512,
                SignatureScheme::ECDSA_NISTP256_SHA256,
                SignatureScheme::ECDSA_NISTP384_SHA384,
                SignatureScheme::ED25519,
                SignatureScheme::RSA_PSS_SHA256,
                SignatureScheme::RSA_PSS_SHA384,
                SignatureScheme::RSA_PSS_SHA512,
            ]
        }
    }
    let cfg = ClientConfig::builder()
        .dangerous()
        .with_custom_certificate_verifier(Arc::new(AcceptAll))
        .with_no_client_auth();
    ureq::AgentBuilder::new().tls_config(Arc::new(cfg)).build()
}

/// Suppress unused-import warnings in tests that don't exercise `Payload`
/// directly. Kept so future test additions can pattern-match on it.
#[allow(dead_code)]
fn _payload_lives_here(_: Payload) {}
